### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by qzsrh** [dvlab-research/ProposeReduce#1]
Hello, I encountered the following error while running the demo:

Traceback (most recent call last):
  File "tools/demo.py", line 192, in <module>
    main()
  File "tools/demo.py", line 189, in main
    single_test(args, infer_paradigm)
  File "tools/demo.py", line 117, in single_test
    seq_masks, seq_scores = infer_paradigm(buffer_data, buffer_meta)
  File "/home/zhangsai/.conda/envs/propose_reduce/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhangsai/propose_reduce/ProposeReduce/tools/ProposeReduce/propose_reduce.py", line 37, in forward
    self.init_buffer(buffer_data)
  File "/home/zhangsai/propose_reduce/ProposeReduce/tools/ProposeReduce/propose_reduce.py", line 77, in init_buffer
    cur_x, cur_x_ori = self.model(return_loss=False, rescale=False, **data)
  File "/home/zhangsai/.conda/envs/propose_reduce/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhangsai/.conda/envs/propose_reduce/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zhangsai/.conda/envs/propose_reduce/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhangsai/propose_reduce/ProposeReduce/tools/../mmdet/models/detectors/base.py", line 92, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/home/zhangsai/propose_reduce/ProposeReduce/tools/../mmdet/models/detectors/base.py", line 84, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/zhangsai/propose_reduce/ProposeReduce/tools/../mmdet/models/detectors/seq_mask_rcnn.py", line 82, in simple_test
    x, x_ori = self.extract_feat(img, ret_ori=True) 
  File "/home/zhangsai/propose_reduce/ProposeReduce/tools/../mmdet/models/detectors/seq_mask_rcnn.py", line 55, in extract_feat
    x = self.backbone(img)
  File "/home/zhangsai/.conda/envs/propose_reduce/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhangsai/propose_reduce/ProposeReduce/tools/../mmdet/models/backbones/resnet.py", line 371, in forward
    x = self.relu(x)
  File "/home/zhangsai/.conda/envs/propose_reduce/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhangsai/.conda/envs/propose_reduce/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 99, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/zhangsai/.conda/envs/propose_reduce/lib/python3.7/site-packages/torch/nn/functional.py", line 941, in relu
    result = torch.relu_(input)
RuntimeError: CUDA error: no kernel image is available for execution on the device

I configured the environment according to the requirements of INSTALL.md

Hope to get your reply！
Thank you very much!!!!!

**Comment by qzsrh** [comment]
> The repo can run well under PyTorch1.1 and CUDA10.0 (we specify cudatoolkit=10.0 in the INSTALL.md). It seems your problem comes from a mismatch between PyTorch version and CUDA version.
> 
> To solve the mismatch problem,
> 
> 1. You can switch to CUDA 10 to use PyTorch1.1.
> 2. Or maybe you need to use a higher-version PyTorch under CUDA 11.1 (But the code have not been tested using other PyTorch version)

I  downloaded CUDA toolkit = 10.0.130 in the virtual environment,

**Comment by HuaijiaLin** [comment]
> > The repo can run well under PyTorch1.1 and CUDA10.0 (we specify cudatoolkit=10.0 in the INSTALL.md). It seems your problem comes from a mismatch between PyTorch version and CUDA version.
> > To solve the mismatch problem,
> > 
> > 1. You can switch to CUDA 10 to use PyTorch1.1.
> > 2. Or maybe you need to use a higher-version PyTorch under CUDA 11.1 (But the code have not been tested using other PyTorch version)
> 
> I downloaded CUDA toolkit = 10.0.130 in the virtual environment,

Can you check whether you have CUDA 10.0 by 'll -h /usr/local'?

**Comment by hechengbo-H** [comment]
I want to ask, if I have cuda=11.1 in ubuntu and I need cuda=10.0 to reproduce the code, if I reproduce it under conda, can't I install cuda=10.0 in the virtual environment? The default is always 11.1?

Thanks

**Comment by HuaijiaLin** [comment]
> I want to ask, if I have cuda=11.1 in ubuntu and I need cuda=10.0 to reproduce the code, if I reproduce it under conda, can't I install cuda=10.0 in the virtual environment? The default is always 11.1?
> 
> Thanks

I am not sure whether you can only install cuda10.0 in the virtual environment. 
But if you have cuda11.1, you may install a higher version PyTorch (maybe >=1.7) to run the code (But the code have not been tested using such higher PyTorch versions)

**Comment by hechengbo-H** [comment]
> > 我想问一下，如果我在ubuntu下有cuda=11.1，我需要cuda=10.0来复现代码，如果我在conda下复现，是不是不能在虚拟环境下安装cuda=10.0？默认总是 11.1？
> > 谢谢
> 
> 我不确定您是否只能在虚拟环境中安装cuda10.0。 但是如果你有cuda11.1，你可能会安装更高版本的PyTorch（可能>=1.7）来运行代码（但代码没有使用这么高的PyTorch版本进行测试）

Thanks for your reply, I will try to run your code in a higher version. Before that, I got the following error, I don't know if you have encountered it? According to the information I checked, this may be due to a problem with too high a cuda version, but I am not sure. Before that I followed the tutorial (INSTALL.md.) and installed it without errors.
Your work is outstanding and I will try to reproduce your code

**Comment by HuaijiaLin** [comment]
> > > 我想问一下，如果我在ubuntu下有cuda=11.1，我需要cuda=10.0来复现代码，如果我在conda下复现，是不是不能在虚拟环境下安装cuda=10.0？默认总是 11.1？
> > > 谢谢
> > 
> > 
> > 我不确定您是否只能在虚拟环境中安装cuda10.0。 但是如果你有cuda11.1，你可能会安装更高版本的PyTorch（可能>=1.7）来运行代码（但代码没有使用这么高的PyTorch版本进行测试）
> 
> Thanks for your reply, I will try to run your code in a higher version. Before that, I got the following error, I don't know if you have encountered it? According to the information I checked, this may be due to a problem with too high a cuda version, but I am not sure. Before that I followed the tutorial (INSTALL.md.) and installed it without errors. Your work is outstanding and I will try to reproduce your co ![bdbad84159f10d966bc23ab1ab7c4af](https://user-images.githubusercontent.com/70620882/140475922-e2c2907b-d7b7-4822-971c-3a98af8a9042.png) de

It seems that the ''nms'' module is not compiled successfully. I think you may meet an error of './compile.sh'  in the installation procedure.

Can you check whether you have an error after typing''./compile.sh'' and give me a screenshot?

**Comment by HuaijiaLin** [comment]
> > Thanks for your reply, I will try to run your code in a higher version. Before that, I got the following error, I don't know if you have encountered it? According to the information I checked, this may be due to a problem with too high a cuda version, but I am not sure. Before that I followed the tutorial (INSTALL.md.) and installed it without errors. Your work is outstanding and I will try to reproduce your co ![bdbad84159f10d966bc23ab1ab7c4af](https://user-images.githubusercontent.com/70620882/140475922-e2c2907b-d7b7-4822-971c-3a98af8a9042.png) de
> 
> It seems that the ''nms'' module is not compiled successfully. I think you may meet an error of './compile.sh' in the installation procedure.
> 
> Can you check whether you have an error after typing''./compile.sh'' and give me a screenshot?

@hechengbo-H You may find an error in ''./compile.sh'' of not finding nvcc. If it is in this case, you need to set the path to correct cuda home (e.g., ''export PATH=/usr/local/cuda/bin:$PATH'').

**Comment by YizeZhao** [comment]
I am having the same issue saying "RuntimeError: CUDA error: no kernel image is available for execution on the device" 
Has anyone managed to solve this? 
I am running the code on google cloud with Nvidia Tesla K80. 
Thank you!

**Comment by HuaijiaLin** [comment]
> I am having the same issue saying "RuntimeError: CUDA error: no kernel image is available for execution on the device" Has anyone managed to solve this? I am running the code on google cloud with Nvidia Tesla K80. Thank you!

@YizeZhao  For this issue, you may need to check whether your PyTorch version matches the CUDA version.

**Comment by YizeZhao** [comment]
> > I am having the same issue saying "RuntimeError: CUDA error: no kernel image is available for execution on the device" Has anyone managed to solve this? I am running the code on google cloud with Nvidia Tesla K80. Thank you!
> 
> @YizeZhao For this issue, you may need to check whether your PyTorch version matches the CUDA version.

Thank you for the reply, for this error I am using CUDA11 and pytorch 1.1.0. 
I have looked up the compatibility table and realized that CUDA 11 only work with pytorch 1.7+. However, I am getting other issue after switching to pytorch 1.7:
![Screen Shot 2021-11-17 at 11 20 11 AM](https://user-images.githubusercontent.com/38020572/142239384-9ccdaf93-7e61-4a6d-89ed-799c351be19f.png)
Do you  know how to solve this?
Thank you.

**Comment by HuaijiaLin** [comment]
> > > I am having the same issue saying "RuntimeError: CUDA error: no kernel image is available for execution on the device" Has anyone managed to solve this? I am running the code on google cloud with Nvidia Tesla K80. Thank you!
> > 
> > 
> > @YizeZhao For this issue, you may need to check whether your PyTorch version matches the CUDA version.
> 
> Thank you for the reply, for this error I am using CUDA11 and pytorch 1.1.0. I have looked up the compatibility table and realized that CUDA 11 only work with pytorch 1.7+. However, I am getting other issue after switching to pytorch 1.7: ![Screen Shot 2021-11-17 at 11 20 11 AM](https://user-images.githubusercontent.com/38020572/142239384-9ccdaf93-7e61-4a6d-89ed-799c351be19f.png) Do you know how to solve this? Thank you.

@YizeZhao I have not met this issue. But it seems that you may need to re-compile ('./compile.sh') after using the new PyTorch1.7 version?

**Comment by YizeZhao** [comment]
> > > > I am having the same issue saying "RuntimeError: CUDA error: no kernel image is available for execution on the device" Has anyone managed to solve this? I am running the code on google cloud with Nvidia Tesla K80. Thank you!
> > > 
> > > 
> > > @YizeZhao For this issue, you may need to check whether your PyTorch version matches the CUDA version.
> > 
> > 
> > Thank you for the reply, for this error I am using CUDA11 and pytorch 1.1.0. I have looked up the compatibility table and realized that CUDA 11 only work with pytorch 1.7+. However, I am getting other issue after switching to pytorch 1.7: ![Screen Shot 2021-11-17 at 11 20 11 AM](https://user-images.githubusercontent.com/38020572/142239384-9ccdaf93-7e61-4a6d-89ed-799c351be19f.png) Do you know how to solve this? Thank you.
> 
> @YizeZhao I have not met this issue. But it seems that you may need to re-compile ('./compile.sh') after using the new PyTorch1.7 version?

Thank you for the help. 
I compiled the code again after installing pyTorch 1.7, the same error persists.

**Comment by HuaijiaLin** [comment]
> Thank you for the help. I compiled the code again after installing pyTorch 1.7, the same error persists.
@YizeZhao Do you see any errors (on the log) when you compiled the codes (e.g., ./compile.sh)?

**Comment by YizeZhao** [comment]
> > Thank you for the help. I compiled the code again after installing pyTorch 1.7, the same error persists.
> 
> @YizeZhao Do you see any errors (on the log) when you compiled the codes (e.g., ./compile.sh)?

I got this error when running ./compile.sh: 
<img width="732" alt="Screen Shot 2021-11-18 at 9 50 03 AM" src="https://user-images.githubusercontent.com/38020572/142438428-0da0fe3b-e3f5-4c91-86c0-f88133a05c9c.png">

**Comment by HuaijiaLin** [comment]
> > > Thank you for the help. I compiled the code again after installing pyTorch 1.7, the same error persists.
> > 
> > 
> > @YizeZhao Do you see any errors (on the log) when you compiled the codes (e.g., ./compile.sh)?
> 
> I got this error when running ./compile.sh: <img alt="Screen Shot 2021-11-18 at 9 50 03 AM" width="732" src="https://user-images.githubusercontent.com/38020572/142438428-0da0fe3b-e3f5-4c91-86c0-f88133a05c9c.png">

You can replace the 'AT_CHECK' with 'TORCH_CHECK' (https://github.com/pytorch/pytorch/issues/36581).

**Comment by YizeZhao** [comment]
> > > > Thank you for the help. I compiled the code again after installing pyTorch 1.7, the same error persists.
> > > 
> > > 
> > > @YizeZhao Do you see any errors (on the log) when you compiled the codes (e.g., ./compile.sh)?
> > 
> > 
> > I got this error when running ./compile.sh: <img alt="Screen Shot 2021-11-18 at 9 50 03 AM" width="732" src="https://user-images.githubusercontent.com/38020572/142438428-0da0fe3b-e3f5-4c91-86c0-f88133a05c9c.png">
> 
> You can replace the 'AT_CHECK' with 'TORCH_CHECK' ([pytorch/pytorch#36581](https://github.com/pytorch/pytorch/issues/36581)).

Hi, thanks for replying, 
After replacing all  'AT_CHECK' with 'TORCH_CHECK', there is no error when running ./compile.sh. However, the "undefined symbol" error persists
![Screen Shot 2021-11-17 at 11 20 11 AM](https://user-images.githubusercontent.com/38020572/142468564-8d4aff2e-9ee7-4150-ac87-1da9f9082e66.png)
.

**Comment by HuaijiaLin** [comment]
> Hi, thanks for replying, After replacing all 'AT_CHECK' with 'TORCH_CHECK', there is no error when running ./compile.sh. However, the "undefined symbol" error persists ![Screen Shot 2021-11-17 at 11 20 11 AM](https://user-images.githubusercontent.com/38020572/142468564-8d4aff2e-9ee7-4150-ac87-1da9f9082e66.png) .

@YizeZhao Hi, I try to reproduce your issue but I do not meet the same issue of "undefined symbol: cudaLaunchKernel".
But luckily, I find a way to compile the codes and run 'sh demo.sh' successfully with PyTorch1.7 && CUDA11 in my machine.
Here are the steps (a modified version of [INSTALL.md](https://github.com/dvlab-research/ProposeReduce/blob/main/INSTALL.md)):

0) make sure you have 'CUDA11' in '/usr/local'
1) create a conda env && install PyTorch1.7
2) to constraint the scopes of packages, I type 'export PYTHONPATH=/path-to-conda-env-pytorch1.7/lib/python3.7/site-packages/'.
3) To run './compile.sh'. 
a) replace the 'AT_CHECK' with 'TORCH_CHECK'  in 'mmdet/ops/roi_align' and 'mmdet/ops/roi_pool'
b) For compile 'nms', I meet 'no nvcc' error. If in this case, I type 'export PATH=/usr/local/cuda/bin:$PATH' and then compile  again.
Make sure you can see '\*-gpu.so' file in each operator of  'mmdet/ops/*'.
4) I try to install 'libs/mmcv/' and 'libs/cocoapi/PythonAPI/' but meet 'Could not find suitable distribution for pytest-runner' error. To solve this problem,
a) Install pytest-runner manually from https://www.cnpython.com/pypi/pytest-runner (python setup.py install). But I meet error of 'ERROR: No matching distribution found for setuptools_scm>=1.15.0'. So I then
b) Install setuptools_scm manually from https://github.com/pypa/setuptools_scm (python setup.py develop).
5) Run 'sh demo.sh' and it succeeds!

I hope it helps you.

**Comment by YizeZhao** [comment]
> > Hi, thanks for replying, After replacing all 'AT_CHECK' with 'TORCH_CHECK', there is no error when running ./compile.sh. However, the "undefined symbol" error persists ![Screen Shot 2021-11-17 at 11 20 11 AM](https://user-images.githubusercontent.com/38020572/142468564-8d4aff2e-9ee7-4150-ac87-1da9f9082e66.png) .
> 
> @YizeZhao Hi, I try to reproduce your issue but I do not meet the same issue of "undefined symbol: cudaLaunchKernel". But luckily, I find a way to compile the codes and run 'sh demo.sh' successfully with PyTorch1.7 && CUDA11 in my machine. Here are the steps (a modified version of [INSTALL.md](https://github.com/dvlab-research/ProposeReduce/blob/main/INSTALL.md)):
> 
> 0. make sure you have 'CUDA11' in '/usr/local'
> 1. create a conda env && install PyTorch1.7
> 2. to constraint the scopes of packages, I type 'export PYTHONPATH=/path-to-conda-env-pytorch1.7/lib/python3.7/site-packages/'.
> 3. To run './compile.sh'.
>    a) replace the 'AT_CHECK' with 'TORCH_CHECK'  in 'mmdet/ops/roi_align' and 'mmdet/ops/roi_pool'
>    b) For compile 'nms', I meet 'no nvcc' error. If in this case, I type 'export PATH=/usr/local/cuda/bin:$PATH' and then compile  again.
>    Make sure you can see 'gpu-related .so file' in each operator of  'mmdet/ops/*'.
> 4. I try to install 'libs/mmcv/' and 'libs/cocoapi/PythonAPI/' but meet 'Could not find suitable distribution for pytest-runner' error. To solve this problem,
>    a) Install pytest-runner manually from https://www.cnpython.com/pypi/pytest-runner (python setup.py install). But I meet error of 'ERROR: No matching distribution found for setuptools_scm>=1.15.0'. So I then
>    b) Install setuptools_scm manually from https://github.com/pypa/setuptools_scm (python setup.py develop).
>    Then I can successfully install 'mmcv' and 'cocoapi'
> 5. run 'python setup.py install --user'
> 6. Run 'sh demo.sh' and it succeeds!
> 
> I hope it helps you.

Thank you very much for your help. Unfortunately, that does not solve my issue. As you managed to reproduce on CUDA 11 without the same error, that probably means there is something wrong with my CUDA. I have re-installed the CUDA again on my machine which did not help. I will keep looking for solutions. Anyways thank you again for the interesting work, I will definitely visit back if I solve my issue.

**Comment by HuaijiaLin** [comment]
> Thank you very much for your help. Unfortunately, that does not solve my issue. As you managed to reproduce on CUDA 11 without the same error, that probably means there is something wrong with my CUDA. I have re-installed the CUDA again on my machine which did not help. I will keep looking for solutions. Anyways thank you again for the interesting work, I will definitely visit back if I solve my issue.

Thanks, good luck to you :-)
