### ISSUE TITLE
how to calculate classification score in non-key frame?

### ISSUE THREAD

**Issue by bxcxa** [dvlab-research/ProposeReduce#5]
hi,
paper says:“For each sequence set Sk , We have its corresponding mask M(Sk) and classification score C(Sk)”. But I don't find anywhere describing how to calculate classification in the non-key frame.
 
The framework of seq mask r-cnn only calculate the mask of non-key frame ，not cls.

Thank you!

**Comment by HuaijiaLin** [comment]
Thanks for your question on details. It seems we do not describe how to obtain the classification score for the non-key frames in the paper.

In the implementation,  for a non-key frame, with its mask given, we first calculate the bounding box of this mask and then apply the classification head (of seq mask r-cnn) to obtain the score for this bbox.

The function [seq_scoring](https://github.com/dvlab-research/ProposeReduce/blob/6bd220f759f211c1ed30e1e7667b3e34d956d1a1/tools/ProposeReduce/propose_reduce.py#L172) describes this procedure.

**Comment by bxcxa** [comment]
get it,thank you&nbsp; for detailed explanation.

---Original---
From: ***@***.***&gt;
Date: Tue, Mar 15, 2022 00:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dvlab-research/ProposeReduce] how to calculate classificationscore in non-key frame? (Issue #5)




 
Thanks for your question on details. It seems we do not describe how to obtain the classification score for the non-key frames in the paper.
 
In the implementation,  for a non-key frame, with its mask given, we first calculate the bounding box of this mask and then apply the classification head (of seq mask r-cnn) to obtain the score for this bbox.
 
The function seq_scoring describes this procedure.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
